# Generated by Django 4.0 on 2022-03-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chapter_video_duration_alter_chapter_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video_duration',
        ),
    ]
