# Generated by Django 4.0 on 2022-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_chapter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_duration',
            field=models.CharField(help_text='Save video duration in seconds', max_length=200, null=True),
        ),
    ]
