# Generated by Django 4.0 on 2022-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_chapter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video_duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
