# Generated by Django 4.0 on 2022-04-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_chapter_video_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_courses', to='main.course')),
            ],
        ),
    ]
