# Generated by Django 4.0 on 2022-04-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_relatedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedCourse',
        ),
    ]
