# Generated by Django 4.0 on 2022-04-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video_duration',
        ),
    ]
