# Generated by Django 4.0 on 2022-04-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_chapter_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
