# Generated by Django 4.0 on 2022-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_attempquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
