# Generated by Django 4.0 on 2022-06-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.BigIntegerField(null=True),
        ),
    ]
