# Generated by Django 4.0 on 2022-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
