# Generated by Django 4.0 on 2022-06-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_course_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='views',
            new_name='course_views',
        ),
    ]
