# Generated by Django 4.0 on 2022-06-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_views_course_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_views',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
