# Generated by Django 4.1.5 on 2023-01-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_rename_instgram_url_teacher_instagram_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='courserating',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courserating',
            name='student',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='studentfavoritecourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentfavoritecourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_views',
        ),
        migrations.RemoveField(
            model_name='course',
            name='techs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_categories',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='website_url',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='CourseRating',
        ),
        migrations.DeleteModel(
            name='StudentFavoriteCourse',
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
