# Generated by Django 4.1.5 on 2023-01-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_chapter_course_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(null=True, upload_to='chair_imgs/')),
            ],
            options={
                'verbose_name_plural': '1. Chairman',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='login_via_otp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='login_via_otp',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='verify_status',
        ),
    ]
