# Generated by Django 4.1.5 on 2023-01-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_chairman_remove_student_login_via_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempquiz',
            options={'verbose_name_plural': '12. Attempted Questions'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '5. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '4. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '11. Course Quiz'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '9. Notifications'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': '8. Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'verbose_name_plural': '10. Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '3. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name_plural': '7. Student Assignments'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '2. Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teacherstudentchat',
            options={'verbose_name_plural': '13. Teacher Student Messages'},
        ),
    ]
